# Base image
FROM openjdk:17-alpine

# Environment Variables
ENV APP_NAME=rinku
ENV APP_HOME=/opt/${APP_NAME}

# Create the application directory
RUN mkdir -p ${APP_HOME}

# Copy the entire project to the image
COPY . ${APP_HOME}

# Set the working directory
WORKDIR ${APP_HOME}

# Start the application on the Tomcat embedded server
CMD ["./mvnw", "spring-boot:run"]